### ISSUE TITLE
Install check out of date (?)

### ISSUE THREAD

**Issue by Neel-Kolhe** [PeterKamphuis/pyFAT-astro#12]
Hello, 

I think the installation check may be out of date, the output suggested to report it here, so here goes!
 
Please find attached the log and final model, apologies if I got anything wrong.

Clear skies and Minimal RFI to you!

[Finalmodel .txt](https://github.com/PeterKamphuis/pyFAT-astro/files/13349855/Finalmodel.txt)

[Log.txt](https://github.com/PeterKamphuis/pyFAT-astro/files/13349836/Log.txt)

**Comment by PeterKamphuis** [comment]
Thank you, from the Log.txt it seems you are running v0.1.1. It seems that there is was something going wrong with the versioning but the current main provides me with an error. I'll try to fix this asap.

**Comment by PeterKamphuis** [comment]
This should now be fixed and pip should instal v0.1.3 which hopefully has an updates installation_check
