### ISSUE TITLE
Error running pyfat-using the example cube NGC_2903 downloaded from pyFAT GITHUB

### ISSUE THREAD

**Issue by bnamumba** [PeterKamphuis/pyFAT-astro#15]
This is version 0.1.3 of pyFAT.
We are using 16 cpus.
        ONE_STEP_CONVERGENCE: For ngc we are starting loop 1 out of maximum 15.

        FAILED_FIT: Tirific failed to produce output in Fit_Tirific_OSC. It might be an unspecified crash.
we try once more else we break off the fitting. As this sometimes happens due to a gsl interpolation error we modify the ring size by 5%

 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
 Waiting for /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.
        RUN_TIRIFIC: After 30 seconds we could not find the expected output from the tirific run. We are raising an error for this galaxy.

        ------------When filing a bug report please copy all output  below this line------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        FAT did not run the full fitting routines for catalog entry ngc.
        Which is the galaxy in directory /scratch3/users/brenda/wlm2/second/.
        Please check this log and output_catalogue carefully for what went wrong.
        The detected exit reason is: "The tirific subprocess did not produce the correct output, most likely it crashed.
We were running Fit_Tirific_OSC_In.def and failed to find the output /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits or /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.def.
".
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

            Your code has crashed for some reason. If this message completely baffles you then please submit the trace back as a bug report to:

            https://github.com/PeterKamphuis/pyFAT/issues

            If the error occured while fitting a galaxy, please attach your fitting log as well

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyFAT_astro/Support/run_functions.py", line 1177, in one_step_converge
    accepted,current_run = sf.run_tirific(Configuration,current_run,\
  File "/usr/local/lib/python3.10/dist-packages/pyFAT_astro/Support/support_functions.py", line 3368, in run_tirific
    raise TirificOutputError(f'''10 minutes after initialization the fitting has still not started.
pyFAT_astro.Support.fat_errors.TirificOutputError: 10 minutes after initialization the fitting has still not started.
We were running Fit_Tirific_OSC_In.def and failed to find the output /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits or /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.def.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyFAT_astro/FAT_Galaxy_Loop.py", line 45, in FAT_Galaxy_Loop
    current_run = runf.fitting_osc(
  File "/usr/local/lib/python3.10/dist-packages/pyFAT_astro/Support/run_functions.py", line 913, in fitting_osc
    current_run = one_step_converge(Configuration, Fits_Files,Tirific_Template,current_run)
  File "/usr/local/lib/python3.10/dist-packages/pyFAT_astro/Support/run_functions.py", line 1180, in one_step_converge
    accepted,current_run = failed_fit(Configuration,Tirific_Template,\
  File "/usr/local/lib/python3.10/dist-packages/pyFAT_astro/Support/run_functions.py", line 868, in failed_fit
    accepted,current_run = sf.run_tirific(Configuration,current_run,stage = stage, fit_type = fit_type)
  File "/usr/local/lib/python3.10/dist-packages/pyFAT_astro/Support/support_functions.py", line 3396, in run_tirific
    raise TirificOutputError(f'''The tirific subprocess did not produce the correct output, most likely it crashed.
pyFAT_astro.Support.fat_errors.TirificOutputError: The tirific subprocess did not produce the correct output, most likely it crashed.
We were running Fit_Tirific_OSC_In.def and failed to find the output /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.fits or /scratch3/users/brenda/wlm2/second//Fit_Tirific_OSC/Fit_Tirific_OSC.def.

Below is the.yml file used. Using default parameters obtained using pyFAT print_examples=True

input:
  main_directory: /scratch3/users/brenda/wlm2/second
  channel_dependency: independent
  catalogue: null
  tirific: tirific
  sofia2: sofia2
  sofia_basename: null
  sofia_dir: null
output:
  log_directory: Logs/12-03-2024
  log_file: Log.txt
  catalogue: pyFAT_results.txt
  new_output: true
  output_quantity: 3
  warp_output: false
  font_file: /usr/share/fonts/truetype/msttcorefonts/Times_New_Roman.ttf
  debug: false
  timing: false
  verbose_log: false
  verbose_screen: false
fitting:
  catalogue_start_id: '-1'
  catalogue_end_id: '-1'
  fitting_stages:
  - Create_FAT_Cube
  - Run_Sofia
  - Fit_Tirific_OSC
  ring_size: 1.1
  fixed_parameters:
  - Z0
  - XPOS
  - YPOS
  - VSYS
  opt_pixel_beam: 4
  distance: -1.0
cube_name: ngc

**Comment by PeterKamphuis** [comment]
@bnamumba Could you add the log file and the file /scratch3/users/brenda/wlm2/second/Fit_Tirific_OSC_In.def.
The latter might be in the log directory as well. I will see if I can reproduce this.

**Comment by bnamumba** [comment]
Dr Brenda Namumba

Wits Centre for Astrophysics

East Campus, University of the Witwatersrand, Yale Rd, Braamfontein,
Johannesburg, 2001

**Comment by bnamumba** [comment]
[Fit_Tirific_OSC_In.def.zip](https://github.com/PeterKamphuis/pyFAT-astro/files/14588294/Fit_Tirific_OSC_In.def.zip)

**Comment by PeterKamphuis** [comment]
@bnamumba Well good new and bad news. I can reproduce the error but I haven't really been able to tie down the issue. I retested with your setup on the pyFAT-Beta branch (v0.1.5) and it is solved in that branch.  I will focus on getting the branch into the main but for testing reasons that might take a week or two. If you intend to use to use the branch for an amount of galaxies that you can inspect afterwards it should be fine to use for most cases.
