### ISSUE TITLE
pyFAT crashed

### ISSUE THREAD

**Issue by ianjarog** [PeterKamphuis/pyFAT-astro#16]
@PeterKamphuis We are still unable to run any of the updated versions. However, using the same command on the **older version** (June 2023, 0.1.1) **works well**...Here is the error I got using the new stable version available from pip (not from github but directly from pip).  

Singularity> pyFAT cube_name="J1106.fits" fitting.distance=12.7 ncpu=15 fitting.fixed_parameters=["Z0","XPOS","YPOS","VSYS"]
This is version 0.1.3 of pyFAT.
We are using 15 cpus.
        ONE_STEP_CONVERGENCE: For J1106 we are starting loop 1 out of maximum 15.

        FAILED_FIT: Tirific failed to produce output in Fit_Tirific_OSC. It might be an unspecified crash.
we try once more else we break off the fitting. As this sometimes happens due to a gsl interpolation error we modify the ring size by 5%

 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
 Waiting for /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits.  
        RUN_TIRIFIC: After 30 seconds we could not find the expected output from the tirific run. We are raising an error for this galaxy.

        ------------When filing a bug report please copy all output  below this line------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        FAT did not run the full fitting routines for catalog entry J1106.
        Which is the galaxy in directory /data/.
        Please check this log and output_catalogue carefully for what went wrong.
        The detected exit reason is: "The tirific subprocess did not produce the correct output, most likely it crashed.
We were running Fit_Tirific_OSC_In.def and failed to find the output /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits or /data//Fit_Tirific_OSC/Fit_Tirific_OSC.def.
".
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

            Your code has crashed for some reason. If this message completely baffles you then please submit the trace back as a bug report to:

            https://github.com/PeterKamphuis/pyFAT/issues  

            If the error occured while fitting a galaxy, please attach your fitting log as well

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/Support/run_functions.py", line 1177, in one_step_converge
    accepted,current_run = sf.run_tirific(Configuration,current_run,\
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/Support/support_functions.py", line 3368, in run_tirific
    raise TirificOutputError(f'''10 minutes after initialization the fitting has still not started.
pyFAT_astro.Support.fat_errors.TirificOutputError: 10 minutes after initialization the fitting has still not started.
We were running Fit_Tirific_OSC_In.def and failed to find the output /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits or /data//Fit_Tirific_OSC/Fit_Tirific_OSC.def.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/FAT_Galaxy_Loop.py", line 45, in FAT_Galaxy_Loop
    current_run = runf.fitting_osc(
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/Support/run_functions.py", line 913, in fitting_osc
    current_run = one_step_converge(Configuration, Fits_Files,Tirific_Template,current_run)
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/Support/run_functions.py", line 1180, in one_step_converge
    accepted,current_run = failed_fit(Configuration,Tirific_Template,\
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/Support/run_functions.py", line 868, in failed_fit
    accepted,current_run = sf.run_tirific(Configuration,current_run,stage = stage, fit_type = fit_type)
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/Support/support_functions.py", line 3396, in run_tirific
    raise TirificOutputError(f'''The tirific subprocess did not produce the correct output, most likely it crashed.
pyFAT_astro.Support.fat_errors.TirificOutputError: The tirific subprocess did not produce the correct output, most likely it crashed.
We were running Fit_Tirific_OSC_In.def and failed to find the output /data//Fit_Tirific_OSC/Fit_Tirific_OSC.fits or /data//Fit_Tirific_OSC/Fit_Tirific_OSC.def.

**Comment by PeterKamphuis** [comment]
@ianjarog correct me if I'm wrong but that is exactly the same error as in issue #15 as it is exactly the same version you are running? pip only gets updated when there is a new release of the main, I'll try to do this asap but I do need to run some tests first.

**Comment by ianjarog** [comment]
> @ianjarog correct me if I'm wrong but that is exactly the same error as in issue #15 as it is exactly the same version you are running? pip only gets updated when there is a new release of the main, I'll try to do this asap but I do need to run some tests first.

@PeterKamphuis  Yep... same thing....

**Comment by PeterKamphuis** [comment]
This should now be sorted in pyFAT-Beta and included in the next release
