### ISSUE TITLE
Velocity is declining: pyFAT beta SoFiA error

### ISSUE THREAD

**Issue by ianjarog** [PeterKamphuis/pyFAT-astro#17]
@PeterKamphuis  Tryied pyFAT-beta with SoFia2 (fitting.fitting_stages="[Sofia_Catalogue, Fit_Tirific_OSC]") and got the following error?

This is version 0.1.5 of pyFAT.
You have indicated to use sofia for using SoFiA 2 but it cannot be found.
Please provide the correct name : sofia2
        CLEAN_HEADER: There is no reference frame defined in your header. This is ok for FAT but WCS might complain.

        CLEAN_HEADER: Your cube has a significant history attached we are removing it for easier interpretation.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/main.py", line 173, in main
    Full_Catalogue = rf.sofia_input_catalogue(Original_Configuration)
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/Support/read_functions.py", line 1366, in sofia_input_catalogue
    raise InputError(f"Your velocity axis is declining this won't work. exiting")
pyFAT_astro.Support.fat_errors.InputError: Your velocity axis is declining this won't work. exiting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyFAT", line 11, in <module>
    main.main(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/main.py", line 296, in main
    raise ProgramError(f'''Something went wrong in the main. This should not happen. Please list an issue on github.''')
pyFAT_astro.Support.fat_errors.ProgramError: Something went wrong in the main. This should not happen. Please list an issue on github.

**Comment by PeterKamphuis** [comment]
Well this error is at least exactly what it says (I hope), if your velocity axis has negative values this would cause problems.

I have been making pyFAT a bit more restrictive on the velocity frames as it is very hard to correct in the correct many between the different frames.

If I follow the code it should work correctly if you add create_fat_cube to the fitting stages.

**Comment by ianjarog** [comment]
> Well this error is at least exactly what it says (I hope), if your velocity axis has negative values this would cause problems.
> 
> I have been making pyFAT a bit more restrictive on the velocity frames as it is very hard to correct in the correct manner between the different frames.
> 
> If I follow the code it should work correctly if you add create_fat_cube to the fitting stages.

**Comment by PeterKamphuis** [comment]
As far as I can see the syntax should be ok. And there is a check on the fitting stages that they are spelled correctly so that should throw an error. But the error cannot be exactly the same though,  before it crashed on "read_functions.py", line 1366, in sofia_input_catalogue" but that line can not be reached when create_fat_cube is set (See https://github.com/PeterKamphuis/pyFAT-astro/blob/82cceeb897d090eccae7fb496cf4bf4859f04bb8/pyFAT_astro/Support/read_functions.py#L1341). Can you copy paste the error you get now?

**Comment by PeterKamphuis** [comment]
pyFAT should now deal with this correctly when setting create_FAT_cube. But when using a Sofia catalogue in principle it is more efficient to make sure the overview cube is fat compliant.
