### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ianjarog** [PeterKamphuis/pyFAT-astro#19]
Hi @PeterKamphuis ,
I was trying to run the latest pyFAT-beta version using the default configuration file, I did not touch anything on the configuration files since I no longer see the cube_name variable in the new set-up. However, after running it, I got the following errors:

Singularity> pyFAT configuration_file=FAT_defaults.yml
This is version 0.1.7 of pyFAT.
You have indicated to use sofia for using SoFiA 2 but it cannot be found.
Please provide the correct name : sofia2
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/main.py", line 175, in main
    Full_Catalogue = rf.catalogue(Original_Configuration['CATALOGUE'],split_char= cfg.advanced.catalogue_split_character)
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/Support/read_functions.py", line 41, in catalogue
    with open(filename,'r') as tmpfile:
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyFAT", line 11, in <module>
    main.main(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/pyFAT_astro/main.py", line 297, in main
    raise ProgramError(f'''Something went wrong in the main. This should not happen. Please list an issue on github.''')
pyFAT_astro.Support.fat_errors.ProgramError: Something went wrong in the main. This should not happen. Please list an issue on github.
Singularity>

**Comment by PeterKamphuis** [comment]
Hi @ianjarog 

yes cube_name is removed from the print_examples. My idea behind is that  you use cube_name from the command line not with the input file and that if you have a catalogue in the yml file.

Just to confirm, you do have cube_name: <cubename> in the yml file as a 0th level entry?

I tried to copy the error but it works for me.

**Comment by ianjarog** [comment]
@PeterKamphuis  So this was just caused by the way I run it, after adding cube_name on command line then it works. 
> Just to confirm, you do have cube_name: <cubename> in the yml file as a 0th level entry?
The default file does not include cube_name and I did not add it myself. For now, I only tried running cube_name on the command line.

**Comment by PeterKamphuis** [comment]
Ah ok, I'll build in a check to warn the user when no input is found.
