### ISSUE TITLE
Fail Check 

### ISSUE THREAD

**Issue by akotodanso** [PeterKamphuis/pyFAT-astro#3]
I get the following error after the test run . I have SoFia-2 working

!!!!---------------------------------------------!!!!!
!!!! FAT ran through the fitting process but the !!!!!
!!!! fitted values differ too much from their    !!!!!
!!!! expectations. Please update SoFiA and other !!!!!
!!!! dependencies. I f you have done so and this !!!!!
!!!! message remains, the check is likely out of !!!!!
!!!! date. If you are unable to resolve the issue!!!!!
!!!! please file a bug report at:                !!!!!
!!!!                                             !!!!!
!!!! https://github.com/PeterKamphuis/pyFAT/issues !!!!!
!!!!                                             !!!!!
!!!! Please add the Log.txt file in the directory!!!!!
!!!!/home/alex/SoFiA-2/FAT_Installation_Check/Logs/23-11-2021/!!!!!
!!!! and the Finalmodel.def.                     !!!!!
!!!!---------------------------------------------!!!!!

[Log.txt](https://github.com/PeterKamphuis/pyFAT-astro/files/7589258/Log.txt)

**Comment by PeterKamphuis** [comment]
Yes the main installation_check it out of date. Thank you for letting me know.

Your log looks like everything is fine and that your installation is ok. If you want to make sure I have updated the check in the pyFAT branch. That version does require one of the latest SoFiA's though.

**Comment by PeterKamphuis** [comment]
This should now be fixed in v0.0.8. If it occurs again please re-open

**Comment by akotodanso** [comment]
Pleasure
